# config/auth.yaml

aws_cognito:
  user_pool_id: "eu-west-1_G5rHco"
  client_id: "3i2edjm6kujd0qt27t41dfe"
  region: "eu-west-1"
  auth_url: "https://cognito-idp.eu-west-1.amazonaws.com/"
credentials:
  # must use username not email
  username: ""
  password: ""
  # device id must be a unique string to identify the device
  device_id: ""
headers:
  content_type: "application/x-amz-json-1.1"
